project:
  type: website
  output-dir: docs

website:
  bread-crumbs: false
  page-navigation: true
  title: "Mineração de Dados"
  sidebar:
    style: "docked"
    search: false
    border: false
    logo: img/mineracao-logo-circ.png
    contents:
    - section: "Informações da disciplina"
      contents: 
      - href: info/dados_gerais.qmd
        text: "Dados gerais"
      - href: info/ementa.qmd
        text: "Ementa e objetivos"
      - href: info/conteudo.qmd
        text: "Conteúdo"
      - href: info/bibliografia.qmd
        text: "Bibliografia"
      - href: info/cronograma.qmd
        text: "Cronograma"
      - href: info/softwares.qmd
        text: "Softwares Necessários"
    
    - section: "Aulas"
      contents: 
      - section: "Parte 1: Fundamentos"
        contents:
          - href: aulas/01-Apresentacao_da_disciplina.qmd
            text: "1- Apresentação da Disciplina"
          - href: aulas/02-introducao_ao_rstudio+github.qmd
            text: "2- Introdução ao RStudio + GitHub"
          - href: aulas/03-introducao_ao_quarto.qmd
            text: "3- Introdução ao Quarto"
          - href: aulas/04-processamento_out-of-core.qmd
            text: "4- Processamento *Out-of-Core*"
          - href: aulas/05-pre-processamento_de_dados.qmd
            text: "5- Pré-Processamento de Dados"
      - section: "Parte 2: Métodos Não Supervisionados"
        contents:
          - href: aulas/06-agrupamento_de_dados_com_k-means_e_metodos_relacionados.qmd
            text: "6- Agrupamento com K-Means e Métodos Relacionados"
      
      #- section: "Parte 2: Métodos de Estimação"
      #  contents:
      #    - href: aulas/11-Metodo_dos_momentos.qmd
      #      text: "11- Método dos Momentos"
      
      #- section: "Parte 3: Estimação por intervalo"
      #  contents:
      #    - href: aulas/1-Apresentacao_da_disciplina.qmd
      #      text: "1- Apresentação da Disciplina e Conceitos Iniciais"
    
    #- href: PDFs/listas/listas_de_exercicio.qmd
    #  text: "Listas de Exercício"
    #- href: PDFs/tabelas/tabelas.qmd
    #  text: "Tabelas"



format:
  html:
    theme: styles.scss
    toc: true
    grid:
      sidebar-width: 300px
resources:
  - PDFs/**